VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThisWorkbook"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True

Private Sub Workbook_BeforeSave(ByVal SaveAsUI As Boolean, Cancel As Boolean)

'Dim rng As Range
'Dim msg As String
'
'Set rng = ThisWorkbook.Worksheets("Cov").Range("D33")
'
'If CInt(rng.Value) * 1 = 0 Then
'    msg = "Checks do not match!"
'    MsgBox msg, vbExclamation, "Checks"
'End If


End Sub
